# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `purdytest` gem.
# Please instead update this file by running `tapioca generate`.

# typed: true

module Purdytest
  class << self
    def configure; end
  end
end

Purdytest::CONFIG = T.let(T.unsafe(nil), T.untyped)

class Purdytest::IO < ::Struct
  def error; end
  def fail; end
  def method_missing(msg, *args); end
  def pass; end
  def print(o); end
  def skip; end
end

Purdytest::IO::COLORS = T.let(T.unsafe(nil), Hash)

Purdytest::VERSION = T.let(T.unsafe(nil), String)
