#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path("../lib", __dir__))
$LOAD_PATH.unshift(File.expand_path("#{Dir.pwd}/test", __dir__))

require "loupe"

Loupe::Cli.new
